In [ ]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import pickle

In [15]:
Urban_station_lonlats = np.array([
['dongsi_aq',116.417,39.929],
['tiantan_aq',116.407,39.886],
['guanyuan_aq',116.339,39.929],
['wanshouxigong_aq',116.352,39.878],
['aotizhongxin_aq',116.397,39.982],
['nongzhanguan_aq',116.461,39.937],
['wanliu_aq',116.287,39.987],
['beibuxinqu_aq',116.174,40.09],
['zhiwuyuan_aq',116.207,40.002],
['fengtaihuayuan_aq',116.279,39.863],
['yungang_aq',116.146,39.824],
['gucheng_aq',116.184,39.914]
])
lons = np.array(Urban_station_lonlats[:,1],dtype = np.float32)
lats = np.array(Urban_station_lonlats[:,2],dtype = np.float32)
print(lons.max(),lons.min(),lons.mean())
print(lats.max(),lats.min(),lats.mean())
X_length = 93.6
Y_length = 41.2
#Change X Y to degree
Y_degree = Y_length / 111
#Consider the length of the latitude line
X_degree = X_length / (40000 * np.cos(lats.mean() / 180 * 3.1415926) / 360)
#X_degree = X_length / 111

116.461 116.146 116.30417
40.09 39.824 39.935085


In [ ]:
lat_step = np.arange(lats.mean() - Y_degree,lats.mean() + Y_degree,.1)
lon_step = np.arange(lons.mean() - X_degree,lons.mean() + X_degree,.1)
#Build the step map
for index in range(len(lat_step)):
    lat_step[index] = round(lat_step[index],1)
for index in range(len(lon_step)):
    lon_step[index] = round(lon_step[index],1)
print(lat_step)
print(lon_step)
#Get the size of point waiting to be analyzed
point_size = len(lat_step) * len(lon_step)
with open("lat_lon_range.pkl","wb") as file:
    pickle.dump((lat_step,lon_step),file)
print("ok")

In [ ]:
#Use panda to read csv
beijing_weather_data = pd.read_csv("Beijing_historical_meo_grid.csv")
print(beijing_weather_data.head())
#Get the value of beijing data
beijing_weather_data_value = beijing_weather_data.values

In [ ]:
from datetime import date
from datetime import datetime
#Build the datetime object
for index in tqdm(range(len(beijing_weather_data_value))):
    beijing_weather_data_value[index][3] = datetime.strptime(
        beijing_weather_data_value[index][3],'%Y-%m-%d %H:%M:%S')

In [ ]:
#Caculate the days between June 31 to March 1
start = date(2017,3,1)
end = date(2017,7,1)
#Set the correct array size
collection_size = point_size * (end - start).days * 24
collection = [None] * collection_size
#Select the data from March to June
def get_Data(beijing_weather_data_value,collection,collection_size):
    print(collection_size)
    cursor = 0
    for index in tqdm(range(beijing_weather_data_value.shape[0])):
        for lat in lat_step:
            for lon in lon_step:
                if (beijing_weather_data_value[index][1] == lon and 
                    beijing_weather_data_value[index][2] == lat and
                    beijing_weather_data_value[index][3].month >= 3 and
                    beijing_weather_data_value[index][3].month <= 6):
                    collection[cursor] = beijing_weather_data_value[index]
                    cursor = cursor + 1
                    if cursor == collection_size:
                        print(cursor)
                        return collection;
#Extract all the data from CSV
collection = get_Data(beijing_weather_data_value,collection,collection_size)
with open("1hour.pkl","wb") as file:
    pickle.dump(collection, file, protocol=pickle.HIGHEST_PROTOCOL)
print('ok!')

In [ ]:
#Read the data
import pickle
collection = list()
with open("1hour.pkl","rb") as file:
    collection = pickle.load(file)
print(collection[0])

In [ ]:
#Prepare datas for SVR
import pickle
from datetime import datetime
print(collection[0][3])
#collection[:,3] = datetime.strptime('%y-%m-%d %H:%M:%S',collection[:,3])
lon = np.zeros(shape = (len(collection)))
lat = np.zeros(shape = (len(collection)))
month = np.zeros(shape = (len(collection)))
date = np.zeros(shape = (len(collection)))
hour = np.zeros(shape = (len(collection)))
temp = np.zeros(shape = (len(collection)))
humid = np.zeros(shape = (len(collection)))
press = np.zeros(shape = (len(collection)))
direct = np.zeros(shape = (len(collection)))
speed = np.zeros(shape = (len(collection)))
for index in tqdm(range(len(collection))):
    lon[index] = collection[index][1]
    lat[index] = collection[index][2]
    month[index] = collection[index][3].month
    date[index] = collection[index][3].day
    hour[index] = collection[index][3].hour
    temp[index] = collection[index][4]
    humid[index] = collection[index][6]
    press[index] = collection[index][5]
    direct[index] = collection[index][7]
    speed[index] = collection[index][8]
lon = np.expand_dims(lon,axis = 1)
lat = np.expand_dims(lat,axis = 1)
month = np.expand_dims(month,axis = 1)
date = np.expand_dims(date,axis = 1)
hour = np.expand_dims(hour,axis = 1)
temp = np.expand_dims(temp,axis = 1)
humid = np.expand_dims(humid,axis = 1)
press = np.expand_dims(press,axis = 1)
direct = np.expand_dims(direct,axis = 1)
speed = np.expand_dims(speed,axis = 1)
X = np.concatenate((lon,lat,month,date,hour,temp,humid,press,direct,speed),axis = 1)
with open("1hour_prepared.pkl","wb") as file:
    pickle.dump(X, file, protocol=pickle.HIGHEST_PROTOCOL)

In [6]:
#Deserialize all the raw grid data
import pickle
with open("1hour_prepared.pkl","rb") as file:
    X = pickle.load(file)
print(X[:10])
print(X.shape)
'''0.經度(longt)
1.緯度(lat)
2.月份(month)
3.小時(hour)
4.溫度(temp)
5.濕度(humidity)
6.氣壓(pressure)
7.風向(wind_direction)
8.風速(wind_speed)'''

[[115.2   39.6    3.     1.     0.    -4.4   35.47 916.13 333.37  22.56]
 [115.2   39.7    3.     1.     0.    -5.79  39.06 905.54 332.07  25.16]
 [115.2   39.8    3.     1.     0.    -7.14  42.96 892.6  330.67  26.78]
 [115.2   39.9    3.     1.     0.    -8.44  47.44 874.98 328.6   26.46]
 [115.2   40.     3.     1.     0.    -9.73  51.93 857.35 326.49  26.17]
 [115.2   40.1    3.     1.     0.    -8.61  48.58 880.25 324.21  27.03]
 [115.2   40.2    3.     1.     0.    -7.48  45.24 903.14 322.07  27.92]
 [115.2   40.3    3.     1.     0.    -6.74  42.42 917.75 322.45  28.27]
 [115.3   39.6    3.     1.     0.    -2.54  32.41 939.33 337.13  17.22]
 [115.3   39.7    3.     1.     0.    -3.58  33.74 938.19 334.49  21.71]]
(515328, 10)


'0.經度(longt)\n1.緯度(lat)\n2.月份(month)\n3.小時(hour)\n4.溫度(temp)\n5.濕度(humidity)\n6.氣壓(pressure)\n7.風向(wind_direction)\n8.風速(wind_speed)'

# SVR analysis

In [ ]:
#SVR analysis
'''X => SVR輸入向量的numpy array，資料必須照著下面的順序:
0.經度(longt)
1.緯度(lat)
2.月份(month)
3.小時(hour)
4.溫度(temp)
5.濕度(humidity)
6.氣壓(pressure)
7.風向(wind_direction)
8.風速(wind_speed)
Y => PM2.5的預測值'''
import pickle
from sklearn.svm import SVR
from sklearn.externals import joblib
import numpy as np

svr = joblib.load('SVR_beijing.pkl')
X = np.array(X, dtype=np.float64)
X_mu = np.array([116.40616279,39.98908696,4.45972151,14.88423765,11.40249715,17.0021192,33.65642229,996.1066705,208.34196307,10.85087688])
X_sigma = np.array([0.28161015,0.22815651,1.14854307,8.88446275,6.90495716,8.44671392,19.41044621,19.83802731,96.65489494,6.85870324])
Y_mu = 59.541867360598516
Y_sigma = 61.21714698899477

Xs = (X - X_mu) / X_sigma #對要輸入的X向量標準化
Y_pdt = svr.predict(Xs) #將標準化後的X向量放入SVR預測
Y = Y_pdt * Y_sigma + Y_mu #對SVR得到的預測值反標準化
print(Y[:10])

In [ ]:
import pickle as pk
with open("1_hr_pm25.pkl","wb") as file:
    pk.dump(Y, file, protocol=pickle.HIGHEST_PROTOCOL)

# Preprocessing

In [26]:
import pickle as pk
import numpy as np
from datetime import date
#load all the prepared data for SVR(to add feature to )
with open("1hour_prepared.pkl","rb") as file:
    X = pickle.load(file)
#load all the SVR data
with open("1_hr_pm25.pkl","rb") as file:
    Y = pk.load(file)
#load the ercise point of latitude and longitude
with open("lat_lon_range.pkl","rb") as file:
    lat_step, lon_step = pk.load(file)
#Y transform to [date][lon][lat]
date_count = (date(2017,7,1) - date(2017,3,1)).days
Y = np.reshape(Y, (24 * date_count,len(lon_step),len(lat_step),1))
temp = np.reshape(X[:,5],Y.shape)
Y = np.concatenate((Y,temp),axis = 3)
#Get the longitude of the target site
target_lon = np.argwhere(lon_step == 39.9)
#Get the latitude of the target site
target_lat = np.argwhere(lat_step == 116.3)
#There  are 256 objects in pickle file and there are 10 pickle files
validation_size = len(Y) - 2560 
#Dump validation data
with open("1hour_pm25_validation_array.pkl","wb") as file:
    pk.dump((Y[-validation_size - 1:-1],Y[-validation_size:,target_lon,target_lat,0]),file)
#Dump testing data
#Assume that batch size is 256
for index in range(1, int(len(Y) / 256)):
    with open("batch_number_" + str(index) + ".pkl","wb") as file:
        if 256 * index >= len(Y):
            end_batch = len(Y) - 1
        else:
            end_batch = 256 * index
        pk.dump((Y[256 * (index - 1):end_batch],#Testing batch
                 Y[256 * (index - 1) + 1:end_batch + 1 ,target_lon,target_lat,0]),file)#Testing label
print("ok!")

ok!


# Start building network

In [27]:
import tensorflow as tf
import numpy as np
import pickle as pk
import os

In [28]:
#print(validation_size)
batch = list()
batch_label = list()
#Serialize all the batch
for index in range(1,11):
    with open("batch_number_" + str(index) + ".pkl","rb") as file:
        batch_read, batch_label_read = pk.load(file)
        batch.append(batch_read)
        batch_label.append(batch_label_read)
#Serialize the area 
with open("lat_lon_range.pkl","rb") as file:
    lat_step, lon_step = pk.load(file)

with open("1hour_pm25_validation_array.pkl","rb") as file:
    X_validation, Y_validation = pk.load(file)
print("================")
print(X_validation.shape)
print(Y_validation.shape)
print("================")
#print(X_validation[-1])
#print(Y_validation[-2])
batch = np.array(batch)
batch_label = np.array(batch_label)
print(batch.shape)
print(batch_label.shape)
print("================")

(368, 22, 8, 2)
(368, 0, 1)
(10, 256, 22, 8, 2)
(10, 256, 0, 1)


In [5]:
#Normalize input data
def normalize(x):
    norm = (x - x.min())/(x.max() - x.min())
    return norm

In [6]:
def Build_CNN(x):
    CNN = tf.layers.conv2d(inputs = x,filters = 64,kernel_size = 3,padding = 'SAME',activation = tf.nn.relu)
    CNN = tf.nn.relu(CNN)
    CNN = tf.layers.conv2d(inputs = CNN, filters = 64,kernel_size = 3,padding = 'SAME',activation = tf.nn.relu)
    CNN = tf.nn.relu(CNN)
    CNN = tf.contrib.layers.flatten(CNN)
    CNN = tf.contrib.layers.fully_connected(CNN,128)
    CNN = tf.nn.relu(CNN)
    CNN = tf.contrib.layers.fully_connected(CNN,128)
    CNN = tf.nn.relu(CNN)
    CNN = tf.contrib.layers.fully_connected(CNN,1)
    return CNN

In [7]:
def print_loss(session,validation_batch,validation_label,loss):
    loss = session.run(loss,feed_dict = {x:validation_batch,y:validation_label})
    print("|loss:{:.7f}".format(loss),"|")
    pass

In [8]:
#Reset the graph
tf.reset_default_graph()
#Input of the network
x = tf.placeholder(tf.float32,shape = (None,len(lon_step),len(lat_step),1), name = 'x')
y = tf.placeholder(tf.float32,shape = (None),name = 'y')
#Build the network
logits = Build_CNN(x)
# Name logits Tensor, so that is can be loaded from disk after training
logits = tf.identity(logits, name='logits')

#Define Loss and optimizer
a = tf.abs(tf.subtract(y,logits))
b = tf.add(y,logits)
loss = tf.scalar_mul(2, tf.reduce_mean(tf.divide(a, b)))
#MSE version 
#loss = tf.sqrt(tf.reduce_mean(tf.losses.mean_squared_error(labels = y,predictions = logits)))
optimizer = tf.train.AdamOptimizer().minimize(loss)


In [9]:
#Loss test
import numpy as np
def smape(actual, predicted):
    a = np.abs(np.array(actual) - np.array(predicted))
    print(a)
    b = np.array(actual) + np.array(predicted)
    print(b)
    print(np.divide(a, b, out=np.zeros_like(a), where=b!=0, casting='unsafe'))
    return 2 * np.mean(np.divide(a, b))
a = np.array([1,2,3,4])
b = np.array([2,99,4,5])
print(smape(a,b))

[ 1 97  1  1]
[  3 101   7   9]
[0 0 0 0]
0.7738488134527738


In [12]:
epoch = 10000
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for e in range(epoch):
        for batch_num in range(0,10):
            sess.run(optimizer,feed_dict = {x:batch[batch_num],y:batch_label[batch_num]})
            loss_value = sess.run(loss,feed_dict = {x:X_validation,y:Y_validation})
        print("|loss:",loss_value,"|")

|loss: 0.48209846 |
|loss: 0.442506 |
|loss: 0.48542574 |
|loss: 0.4442621 |
|loss: 0.43022144 |
|loss: 0.43439505 |
|loss: 0.4602072 |
|loss: 0.44819877 |
|loss: 0.4368088 |
|loss: 0.43895948 |
|loss: 0.443519 |
|loss: 0.45190883 |
|loss: 0.45693353 |
|loss: 0.4464655 |
|loss: 0.44241923 |
|loss: 0.42749986 |
|loss: 0.4224245 |
|loss: 0.4315503 |
|loss: 0.4902531 |
|loss: 0.4634153 |
|loss: 0.4490166 |
|loss: 0.43608442 |
|loss: 0.4273219 |
|loss: 0.43310893 |
|loss: 0.44861692 |
|loss: 0.4803127 |
|loss: 0.43568167 |
|loss: 0.42385647 |
|loss: 0.42724696 |
|loss: 0.4691205 |
|loss: 0.46190044 |
|loss: 0.41920206 |
|loss: 0.42598578 |
|loss: 0.46230626 |
|loss: 0.46011397 |
|loss: 0.4175265 |
|loss: 0.42792022 |
|loss: 0.4629006 |
|loss: 0.45297253 |
|loss: 0.41959438 |
|loss: 0.43478912 |
|loss: 0.4613104 |
|loss: 0.44690162 |
|loss: 0.42054546 |
|loss: 0.43664443 |
|loss: 0.4628848 |
|loss: 0.4405825 |
|loss: 0.42173812 |
|loss: 0.43500656 |
|loss: 0.45606863 |
|loss: 0.43588084 |
|

|loss: 0.44169262 |
|loss: 0.41532955 |
|loss: 0.42684665 |
|loss: 0.44032416 |
|loss: 0.42327237 |
|loss: 0.42122012 |
|loss: 0.44104728 |
|loss: 0.42437032 |
|loss: 0.43179652 |
|loss: 0.4334602 |
|loss: 0.4217238 |
|loss: 0.4352814 |
|loss: 0.43542665 |
|loss: 0.42090055 |
|loss: 0.43330973 |
|loss: 0.43381423 |
|loss: 0.4218428 |
|loss: 0.43466884 |
|loss: 0.43077737 |
|loss: 0.42353576 |
|loss: 0.43598378 |
|loss: 0.42894527 |
|loss: 0.4227918 |
|loss: 0.43369284 |
|loss: 0.4298316 |
|loss: 0.42484707 |
|loss: 0.42989707 |
|loss: 0.4299608 |
|loss: 0.42394742 |
|loss: 0.429701 |
|loss: 0.43271863 |
|loss: 0.42354476 |
|loss: 0.42757022 |
|loss: 0.43514034 |
|loss: 0.42402688 |
|loss: 0.42355826 |
|loss: 0.43747035 |
|loss: 0.42834768 |
|loss: 0.41977918 |
|loss: 0.4419042 |
|loss: 0.42942005 |
|loss: 0.41828918 |
|loss: 0.4404003 |
|loss: 0.42671415 |
|loss: 0.41955823 |
|loss: 0.43810242 |
|loss: 0.43005508 |
|loss: 0.41555163 |
|loss: 0.44179192 |
|loss: 0.4383844 |
|loss: 0.418

|loss: 0.4238747 |
|loss: 0.42583868 |
|loss: 0.42863658 |
|loss: 0.4241806 |
|loss: 0.42942256 |
|loss: 0.4324875 |
|loss: 0.42307878 |
|loss: 0.42611423 |
|loss: 0.43608034 |
|loss: 0.42361796 |
|loss: 0.42310262 |
|loss: 0.4348513 |
|loss: 0.4313558 |
|loss: 0.4194613 |
|loss: 0.43316555 |
|loss: 0.43209538 |
|loss: 0.41931283 |
|loss: 0.4318704 |
|loss: 0.434872 |
|loss: 0.42191568 |
|loss: 0.43337587 |
|loss: 0.4300784 |
|loss: 0.42744446 |
|loss: 0.4277284 |
|loss: 0.4346154 |
|loss: 0.4278078 |
|loss: 0.42635608 |
|loss: 0.43018737 |
|loss: 0.42153406 |
|loss: 0.4231338 |
|loss: 0.4357342 |
|loss: 0.41968822 |
|loss: 0.42201647 |
|loss: 0.43716446 |
|loss: 0.426059 |
|loss: 0.41878706 |
|loss: 0.43289664 |
|loss: 0.43398315 |
|loss: 0.4212725 |
|loss: 0.4363912 |
|loss: 0.4328189 |
|loss: 0.42982885 |
|loss: 0.43464035 |
|loss: 0.42548344 |
|loss: 0.42018145 |
|loss: 0.43518916 |
|loss: 0.4231032 |
|loss: 0.42028826 |
|loss: 0.4354304 |
|loss: 0.42741418 |
|loss: 0.42019284 |
|l

|loss: 0.42638645 |
|loss: 0.4198851 |
|loss: 0.4280763 |
|loss: 0.43034974 |
|loss: 0.41880244 |
|loss: 0.42582798 |
|loss: 0.4311199 |
|loss: 0.42115623 |
|loss: 0.4227794 |
|loss: 0.43076032 |
|loss: 0.4234062 |
|loss: 0.4204387 |
|loss: 0.42970636 |
|loss: 0.42766106 |
|loss: 0.4198268 |
|loss: 0.42729518 |
|loss: 0.4315343 |
|loss: 0.4223341 |
|loss: 0.4231769 |
|loss: 0.43054157 |
|loss: 0.4246948 |
|loss: 0.42057034 |
|loss: 0.43149647 |
|loss: 0.42935562 |
|loss: 0.42264947 |
|loss: 0.4290166 |
|loss: 0.42971253 |
|loss: 0.42113844 |
|loss: 0.42621532 |
|loss: 0.4350624 |
|loss: 0.42332917 |
|loss: 0.41986325 |
|loss: 0.42875782 |
|loss: 0.4319652 |
|loss: 0.4184304 |
|loss: 0.42744076 |
|loss: 0.4356426 |
|loss: 0.42164746 |
|loss: 0.42554858 |
|loss: 0.43223402 |
|loss: 0.42316598 |
|loss: 0.42546177 |
|loss: 0.43196693 |
|loss: 0.42151955 |
|loss: 0.4252247 |
|loss: 0.43491814 |
|loss: 0.4264912 |
|loss: 0.42284146 |
|loss: 0.43223044 |
|loss: 0.4308755 |
|loss: 0.42084467 |

|loss: 0.43953723 |
|loss: 0.41893154 |
|loss: 0.4220505 |
|loss: 0.43131077 |
|loss: 0.4245094 |
|loss: 0.4225753 |
|loss: 0.43312117 |
|loss: 0.42157966 |
|loss: 0.41821223 |
|loss: 0.42876628 |
|loss: 0.43035078 |
|loss: 0.41938904 |
|loss: 0.42626926 |
|loss: 0.4313296 |
|loss: 0.4201416 |
|loss: 0.4265028 |
|loss: 0.429788 |
|loss: 0.42018706 |
|loss: 0.42877123 |
|loss: 0.42804453 |
|loss: 0.42000023 |
|loss: 0.4306111 |
|loss: 0.42229378 |
|loss: 0.42030263 |
|loss: 0.42816517 |
|loss: 0.4242041 |
|loss: 0.419786 |
|loss: 0.42858684 |
|loss: 0.42486542 |
|loss: 0.42012507 |
|loss: 0.4252034 |
|loss: 0.42563123 |
|loss: 0.42169136 |
|loss: 0.42335957 |
|loss: 0.4253518 |
|loss: 0.4224393 |
|loss: 0.42280146 |
|loss: 0.42580652 |
|loss: 0.42346194 |
|loss: 0.4218842 |
|loss: 0.42550823 |
|loss: 0.42445618 |
|loss: 0.4213722 |
|loss: 0.42372563 |
|loss: 0.42606944 |
|loss: 0.42050475 |
|loss: 0.42240703 |
|loss: 0.42658016 |
|loss: 0.42216682 |
|loss: 0.42101294 |
|loss: 0.4261378 

|loss: 0.42645434 |
|loss: 0.4219979 |
|loss: 0.4211986 |
|loss: 0.42657432 |
|loss: 0.42466614 |
|loss: 0.4216513 |
|loss: 0.42435795 |
|loss: 0.4264675 |
|loss: 0.42184392 |
|loss: 0.42114055 |
|loss: 0.4271799 |
|loss: 0.42202923 |
|loss: 0.42084894 |
|loss: 0.42634374 |
|loss: 0.42527875 |
|loss: 0.42054662 |
|loss: 0.42315346 |
|loss: 0.4267822 |
|loss: 0.42170104 |
|loss: 0.4206161 |
|loss: 0.42657036 |
|loss: 0.4244556 |
|loss: 0.41991255 |
|loss: 0.42391503 |
|loss: 0.4265793 |
|loss: 0.4214448 |
|loss: 0.4203611 |
|loss: 0.42714295 |
|loss: 0.42311254 |
|loss: 0.41956976 |
|loss: 0.4255444 |
|loss: 0.42758238 |
|loss: 0.4207425 |
|loss: 0.42060512 |
|loss: 0.428637 |
|loss: 0.42195904 |
|loss: 0.4197334 |
|loss: 0.4268168 |
|loss: 0.4277816 |
|loss: 0.41982377 |
|loss: 0.4228512 |
|loss: 0.42892992 |
|loss: 0.42198604 |
|loss: 0.4204737 |
|loss: 0.4260489 |
|loss: 0.428782 |
|loss: 0.4188983 |
|loss: 0.42299154 |
|loss: 0.42898098 |
|loss: 0.4223258 |
|loss: 0.42142522 |
|loss

|loss: 0.4239133 |
|loss: 0.42532724 |
|loss: 0.42075014 |
|loss: 0.42148653 |
|loss: 0.426421 |
|loss: 0.4223718 |
|loss: 0.4198896 |
|loss: 0.42439795 |
|loss: 0.42593744 |
|loss: 0.42000657 |
|loss: 0.42133272 |
|loss: 0.4266045 |
|loss: 0.42200342 |
|loss: 0.41904438 |
|loss: 0.42400134 |
|loss: 0.42628846 |
|loss: 0.4205967 |
|loss: 0.42065448 |
|loss: 0.42594776 |
|loss: 0.422021 |
|loss: 0.42017382 |
|loss: 0.42546982 |
|loss: 0.42657247 |
|loss: 0.41978753 |
|loss: 0.4237546 |
|loss: 0.4279432 |
|loss: 0.42218626 |
|loss: 0.42055506 |
|loss: 0.42688033 |
|loss: 0.42704576 |
|loss: 0.41929388 |
|loss: 0.42357317 |
|loss: 0.42810842 |
|loss: 0.42124814 |
|loss: 0.42272648 |
|loss: 0.42913237 |
|loss: 0.42176902 |
|loss: 0.42105302 |
|loss: 0.42843953 |
|loss: 0.42333716 |
|loss: 0.42093903 |
|loss: 0.42777354 |
|loss: 0.422882 |
|loss: 0.4196357 |
|loss: 0.42765108 |
|loss: 0.42313296 |
|loss: 0.4181465 |
|loss: 0.4252852 |
|loss: 0.42633325 |
|loss: 0.4216211 |
|loss: 0.42252973

|loss: 0.42132857 |
|loss: 0.41998252 |
|loss: 0.42576858 |
|loss: 0.42553997 |
|loss: 0.42031753 |
|loss: 0.42146388 |
|loss: 0.4264176 |
|loss: 0.42194188 |
|loss: 0.42041254 |
|loss: 0.42636842 |
|loss: 0.42290562 |
|loss: 0.42009073 |
|loss: 0.42496094 |
|loss: 0.42406586 |
|loss: 0.42010248 |
|loss: 0.42294973 |
|loss: 0.42480835 |
|loss: 0.42128646 |
|loss: 0.42100075 |
|loss: 0.42591545 |
|loss: 0.42113045 |
|loss: 0.42007592 |
|loss: 0.42678893 |
|loss: 0.42242128 |
|loss: 0.419872 |
|loss: 0.42421806 |
|loss: 0.42564204 |
|loss: 0.42083323 |
|loss: 0.42087445 |
|loss: 0.42593595 |
|loss: 0.42234042 |
|loss: 0.41930228 |
|loss: 0.42451328 |
|loss: 0.4244157 |
|loss: 0.41942015 |
|loss: 0.42253697 |
|loss: 0.42522827 |
|loss: 0.4224833 |
|loss: 0.42213696 |
|loss: 0.4244667 |
|loss: 0.42094845 |
|loss: 0.4199851 |
|loss: 0.4270838 |
|loss: 0.42363703 |
|loss: 0.4178033 |
|loss: 0.4253966 |
|loss: 0.4255288 |
|loss: 0.41913614 |
|loss: 0.42183793 |
|loss: 0.42884848 |
|loss: 0.42

|loss: 0.42078295 |
|loss: 0.42374772 |
|loss: 0.42491156 |
|loss: 0.4220563 |
|loss: 0.4214488 |
|loss: 0.426363 |
|loss: 0.4231308 |
|loss: 0.42087197 |
|loss: 0.42370927 |
|loss: 0.42512694 |
|loss: 0.4224149 |
|loss: 0.42112982 |
|loss: 0.42624122 |
|loss: 0.42280442 |
|loss: 0.42102095 |
|loss: 0.42368835 |
|loss: 0.425099 |
|loss: 0.42222828 |
|loss: 0.42082095 |
|loss: 0.4264197 |
|loss: 0.4229374 |
|loss: 0.42079148 |
|loss: 0.42349783 |
|loss: 0.42569146 |
|loss: 0.42196274 |
|loss: 0.4208659 |
|loss: 0.42643833 |
|loss: 0.42239588 |
|loss: 0.42090774 |
|loss: 0.42382172 |
|loss: 0.42534435 |
|loss: 0.42175648 |
|loss: 0.421192 |
|loss: 0.4266919 |
|loss: 0.42272374 |
|loss: 0.42115355 |
|loss: 0.42486444 |
|loss: 0.42589173 |
|loss: 0.4213407 |
|loss: 0.42091417 |
|loss: 0.4263235 |
|loss: 0.42381918 |
|loss: 0.4204173 |
|loss: 0.4257869 |
|loss: 0.42729723 |
|loss: 0.42134047 |
|loss: 0.42158154 |
|loss: 0.427071 |
|loss: 0.42300484 |
|loss: 0.41849 |
|loss: 0.42559174 |
|lo

|loss: 0.4234031 |
|loss: 0.4233104 |
|loss: 0.4305191 |
|loss: 0.42194825 |
|loss: 0.42070818 |
|loss: 0.42934787 |
|loss: 0.42403993 |
|loss: 0.4217658 |
|loss: 0.42817682 |
|loss: 0.42616037 |
|loss: 0.42217156 |
|loss: 0.42603293 |
|loss: 0.42629418 |
|loss: 0.42171147 |
|loss: 0.42366686 |
|loss: 0.4274085 |
|loss: 0.42338192 |
|loss: 0.42292055 |
|loss: 0.42728484 |
|loss: 0.42355165 |
|loss: 0.42214242 |
|loss: 0.42649674 |
|loss: 0.42449063 |
|loss: 0.42343664 |
|loss: 0.4244187 |
|loss: 0.42637593 |
|loss: 0.42337927 |
|loss: 0.42208636 |
|loss: 0.4276372 |
|loss: 0.42410186 |
|loss: 0.42178234 |
|loss: 0.42525128 |
|loss: 0.4252965 |
|loss: 0.42246437 |
|loss: 0.4233412 |
|loss: 0.42727295 |
|loss: 0.42405036 |
|loss: 0.42149717 |
|loss: 0.42480707 |
|loss: 0.42585993 |
|loss: 0.42233607 |
|loss: 0.4221794 |
|loss: 0.4274478 |
|loss: 0.42334014 |
|loss: 0.42141816 |
|loss: 0.42554873 |
|loss: 0.42528814 |
|loss: 0.42246798 |
|loss: 0.4231854 |
|loss: 0.42673326 |
|loss: 0.424

|loss: 0.42638797 |
|loss: 0.42593387 |
|loss: 0.42257786 |
|loss: 0.4259421 |
|loss: 0.4260416 |
|loss: 0.42279017 |
|loss: 0.42434937 |
|loss: 0.42619446 |
|loss: 0.423866 |
|loss: 0.42392346 |
|loss: 0.42646223 |
|loss: 0.42415228 |
|loss: 0.4237268 |
|loss: 0.42622948 |
|loss: 0.42472655 |
|loss: 0.42406645 |
|loss: 0.4245069 |
|loss: 0.42647842 |
|loss: 0.42340654 |
|loss: 0.42295873 |
|loss: 0.42685685 |
|loss: 0.42385805 |
|loss: 0.42287183 |
|loss: 0.4261951 |
|loss: 0.4242413 |
|loss: 0.42381424 |
|loss: 0.4243129 |
|loss: 0.42637727 |
|loss: 0.42374218 |
|loss: 0.42275977 |
|loss: 0.42679122 |
|loss: 0.42401874 |
|loss: 0.42323878 |
|loss: 0.42455092 |
|loss: 0.42629963 |
|loss: 0.42350563 |
|loss: 0.42232323 |
|loss: 0.42703965 |
|loss: 0.42387974 |
|loss: 0.42234388 |
|loss: 0.42468777 |
|loss: 0.42584947 |
|loss: 0.4230724 |
|loss: 0.4223897 |
|loss: 0.4273016 |
|loss: 0.42321554 |
|loss: 0.4218712 |
|loss: 0.4250073 |
|loss: 0.42491913 |
|loss: 0.42319566 |
|loss: 0.42337

|loss: 0.42122802 |
|loss: 0.4287288 |
|loss: 0.42428863 |
|loss: 0.42163315 |
|loss: 0.42675048 |
|loss: 0.42530814 |
|loss: 0.4205819 |
|loss: 0.42373967 |
|loss: 0.42880818 |
|loss: 0.4224496 |
|loss: 0.4220041 |
|loss: 0.42881024 |
|loss: 0.4247598 |
|loss: 0.4204953 |
|loss: 0.42727348 |
|loss: 0.42588812 |
|loss: 0.42212668 |
|loss: 0.42489034 |
|loss: 0.4251358 |
|loss: 0.42310405 |
|loss: 0.42451763 |
|loss: 0.42710257 |
|loss: 0.42363763 |
|loss: 0.42205933 |
|loss: 0.4266226 |
|loss: 0.42291322 |
|loss: 0.4212862 |
|loss: 0.4281397 |
|loss: 0.42368472 |
|loss: 0.42200404 |
|loss: 0.4271892 |
|loss: 0.42504612 |
|loss: 0.4210938 |
|loss: 0.42610794 |
|loss: 0.4277253 |
|loss: 0.4203228 |
|loss: 0.42218947 |
|loss: 0.42785174 |
|loss: 0.4219222 |
|loss: 0.41994694 |
|loss: 0.42655194 |
|loss: 0.4243086 |
|loss: 0.42023945 |
|loss: 0.42463934 |
|loss: 0.4242739 |
|loss: 0.4213047 |
|loss: 0.4250428 |
|loss: 0.4240941 |
|loss: 0.42120808 |
|loss: 0.42510316 |
|loss: 0.42407227 |


|loss: 0.4235453 |
|loss: 0.42813826 |
|loss: 0.42149553 |
|loss: 0.42220423 |
|loss: 0.42968532 |
|loss: 0.4219409 |
|loss: 0.4217146 |
|loss: 0.42977798 |
|loss: 0.42150658 |
|loss: 0.4229101 |
|loss: 0.428359 |
|loss: 0.42110318 |
|loss: 0.42100963 |
|loss: 0.42883286 |
|loss: 0.42388114 |
|loss: 0.42201772 |
|loss: 0.42705223 |
|loss: 0.4226921 |
|loss: 0.42177156 |
|loss: 0.4280325 |
|loss: 0.42257655 |
|loss: 0.42286193 |
|loss: 0.4278903 |
|loss: 0.42225987 |
|loss: 0.4237761 |
|loss: 0.42665404 |
|loss: 0.42293072 |
|loss: 0.42447606 |
|loss: 0.42668715 |
|loss: 0.42068803 |
|loss: 0.42343938 |
|loss: 0.42572704 |
|loss: 0.42252883 |
|loss: 0.4238089 |
|loss: 0.4272758 |
|loss: 0.42148083 |
|loss: 0.42272553 |
|loss: 0.42629242 |
|loss: 0.4215628 |
|loss: 0.42273897 |
|loss: 0.42679632 |
|loss: 0.4223496 |
|loss: 0.42278284 |
|loss: 0.42600614 |
|loss: 0.42428187 |
|loss: 0.4235006 |
|loss: 0.42463717 |
|loss: 0.42587945 |
|loss: 0.42346987 |
|loss: 0.42305163 |
|loss: 0.426482

|loss: 0.42213637 |
|loss: 0.42554575 |
|loss: 0.42847344 |
|loss: 0.42148283 |
|loss: 0.42175382 |
|loss: 0.42758575 |
|loss: 0.42226872 |
|loss: 0.42144984 |
|loss: 0.42731732 |
|loss: 0.42381227 |
|loss: 0.42146164 |
|loss: 0.42606962 |
|loss: 0.4266394 |
|loss: 0.42027032 |
|loss: 0.42412096 |
|loss: 0.42760655 |
|loss: 0.4219163 |
|loss: 0.42072433 |
|loss: 0.42729512 |
|loss: 0.42470008 |
|loss: 0.42238614 |
|loss: 0.42637554 |
|loss: 0.42557982 |
|loss: 0.42297262 |
|loss: 0.4249479 |
|loss: 0.4279043 |
|loss: 0.42418742 |
|loss: 0.42307696 |
|loss: 0.42797014 |
|loss: 0.4227058 |
|loss: 0.4225117 |
|loss: 0.42774814 |
|loss: 0.42451563 |
|loss: 0.4223671 |
|loss: 0.42697152 |
|loss: 0.42307344 |
|loss: 0.42231137 |
|loss: 0.42733374 |
|loss: 0.42532662 |
|loss: 0.42225763 |
|loss: 0.4257544 |
|loss: 0.4258466 |
|loss: 0.4224671 |
|loss: 0.4240555 |
|loss: 0.42784435 |
|loss: 0.42382124 |
|loss: 0.422324 |
|loss: 0.42704704 |
|loss: 0.42285383 |
|loss: 0.42226925 |
|loss: 0.4275

|loss: 0.42729738 |
|loss: 0.42204762 |
|loss: 0.42123082 |
|loss: 0.42828488 |
|loss: 0.42307684 |
|loss: 0.42130458 |
|loss: 0.42636156 |
|loss: 0.4263856 |
|loss: 0.42230058 |
|loss: 0.42423102 |
|loss: 0.42694592 |
|loss: 0.42247924 |
|loss: 0.42240572 |
|loss: 0.42716676 |
|loss: 0.42354184 |
|loss: 0.4225159 |
|loss: 0.42686865 |
|loss: 0.4239135 |
|loss: 0.42171857 |
|loss: 0.4257924 |
|loss: 0.42320058 |
|loss: 0.42286813 |
|loss: 0.42641282 |
|loss: 0.42529958 |
|loss: 0.42301193 |
|loss: 0.42519173 |
|loss: 0.42781147 |
|loss: 0.4208279 |
|loss: 0.4231615 |
|loss: 0.42942494 |
|loss: 0.4236618 |
|loss: 0.42217186 |
|loss: 0.42760512 |
|loss: 0.42131454 |
|loss: 0.4224404 |
|loss: 0.42839164 |
|loss: 0.4239274 |
|loss: 0.4228455 |
|loss: 0.4268127 |
|loss: 0.42528132 |
|loss: 0.42260152 |
|loss: 0.42503735 |
|loss: 0.42655647 |
|loss: 0.4235526 |
|loss: 0.42373067 |
|loss: 0.42839095 |
|loss: 0.42186335 |
|loss: 0.42265844 |
|loss: 0.4292121 |
|loss: 0.42300466 |
|loss: 0.4234

|loss: 0.42643633 |
|loss: 0.42193002 |
|loss: 0.4217909 |
|loss: 0.42668286 |
|loss: 0.4232771 |
|loss: 0.4222918 |
|loss: 0.42461947 |
|loss: 0.42508733 |
|loss: 0.42283595 |
|loss: 0.42236835 |
|loss: 0.42696416 |
|loss: 0.4245612 |
|loss: 0.42131484 |
|loss: 0.42383555 |
|loss: 0.42625725 |
|loss: 0.4226618 |
|loss: 0.42199844 |
|loss: 0.4260029 |
|loss: 0.42315012 |
|loss: 0.42215943 |
|loss: 0.42455673 |
|loss: 0.42488685 |
|loss: 0.4227708 |
|loss: 0.42216036 |
|loss: 0.4269301 |
|loss: 0.4239556 |
|loss: 0.4209721 |
|loss: 0.4237545 |
|loss: 0.42606038 |
|loss: 0.4223678 |
|loss: 0.42182887 |
|loss: 0.42658684 |
|loss: 0.42328587 |
|loss: 0.4222498 |
|loss: 0.42465165 |
|loss: 0.4255294 |
|loss: 0.42291883 |
|loss: 0.42200497 |
|loss: 0.42737263 |
|loss: 0.42443272 |
|loss: 0.42152166 |
|loss: 0.4235923 |
|loss: 0.4271743 |
|loss: 0.4228687 |
|loss: 0.4216964 |
|loss: 0.42626974 |
|loss: 0.42373273 |
|loss: 0.42307094 |
|loss: 0.42398214 |
|loss: 0.4259522 |
|loss: 0.42340034 |

|loss: 0.42177346 |
|loss: 0.4261255 |
|loss: 0.4246556 |
|loss: 0.42252916 |
|loss: 0.4264203 |
|loss: 0.42503345 |
|loss: 0.42436773 |
|loss: 0.4279631 |
|loss: 0.4262219 |
|loss: 0.42316893 |
|loss: 0.4256877 |
|loss: 0.42766777 |
|loss: 0.42303643 |
|loss: 0.42361718 |
|loss: 0.42904383 |
|loss: 0.42430246 |
|loss: 0.422891 |
|loss: 0.42796826 |
|loss: 0.4236385 |
|loss: 0.42342043 |
|loss: 0.42778522 |
|loss: 0.42539153 |
|loss: 0.42396066 |
|loss: 0.42486766 |
|loss: 0.4273115 |
|loss: 0.4243881 |
|loss: 0.42341182 |
|loss: 0.42579156 |
|loss: 0.4269672 |
|loss: 0.423973 |
|loss: 0.4231799 |
|loss: 0.42782894 |
|loss: 0.4245274 |
|loss: 0.42343456 |
|loss: 0.42516595 |
|loss: 0.42781776 |
|loss: 0.42434865 |
|loss: 0.42257932 |
|loss: 0.42631486 |
|loss: 0.42735764 |
|loss: 0.42403537 |
|loss: 0.42258757 |
|loss: 0.4272905 |
|loss: 0.42467195 |
|loss: 0.42272314 |
|loss: 0.42485327 |
|loss: 0.4277375 |
|loss: 0.4243515 |
|loss: 0.42243013 |
|loss: 0.42600903 |
|loss: 0.4244705 |


|loss: 0.42279842 |
|loss: 0.42698982 |
|loss: 0.42391756 |
|loss: 0.42334375 |
|loss: 0.42565137 |
|loss: 0.4268051 |
|loss: 0.42395976 |
|loss: 0.4233283 |
|loss: 0.4291106 |
|loss: 0.42478937 |
|loss: 0.42149255 |
|loss: 0.42421123 |
|loss: 0.4263349 |
|loss: 0.42423198 |
|loss: 0.42271653 |
|loss: 0.42649734 |
|loss: 0.42336127 |
|loss: 0.42292738 |
|loss: 0.42604244 |
|loss: 0.42558655 |
|loss: 0.42372665 |
|loss: 0.42366517 |
|loss: 0.4269273 |
|loss: 0.42459416 |
|loss: 0.42256728 |
|loss: 0.42503834 |
|loss: 0.42765033 |
|loss: 0.4236801 |
|loss: 0.42236823 |
|loss: 0.42739773 |
|loss: 0.4252868 |
|loss: 0.4228647 |
|loss: 0.42460936 |
|loss: 0.4266024 |
|loss: 0.42408848 |
|loss: 0.4222077 |
|loss: 0.42631212 |
|loss: 0.4235862 |
|loss: 0.4231186 |
|loss: 0.42609876 |
|loss: 0.42635974 |
|loss: 0.42269552 |
|loss: 0.4230013 |
|loss: 0.42856446 |
|loss: 0.42554757 |
|loss: 0.4220432 |
|loss: 0.42426458 |
|loss: 0.4263309 |
|loss: 0.42342022 |
|loss: 0.4237487 |
|loss: 0.4272214

|loss: 0.42394772 |
|loss: 0.42396104 |
|loss: 0.42877898 |
|loss: 0.42772037 |
|loss: 0.42348886 |
|loss: 0.42582968 |
|loss: 0.4279735 |
|loss: 0.42566183 |
|loss: 0.42416313 |
|loss: 0.42791623 |
|loss: 0.42544016 |
|loss: 0.42445037 |
|loss: 0.4268931 |
|loss: 0.42665115 |
|loss: 0.42496616 |
|loss: 0.42485115 |
|loss: 0.42850718 |
|loss: 0.42576128 |
|loss: 0.42454377 |
|loss: 0.42797297 |
|loss: 0.42807347 |
|loss: 0.42402413 |
|loss: 0.42458078 |
|loss: 0.42904198 |
|loss: 0.4257627 |
|loss: 0.42387515 |
|loss: 0.42863986 |
|loss: 0.427688 |
|loss: 0.42411244 |
|loss: 0.42551297 |
|loss: 0.42912164 |
|loss: 0.4259057 |
|loss: 0.4239203 |
|loss: 0.42773706 |
|loss: 0.42759582 |
|loss: 0.42448744 |
|loss: 0.4255445 |
|loss: 0.42903954 |
|loss: 0.42567447 |
|loss: 0.42351797 |
|loss: 0.42789623 |
|loss: 0.42739764 |
|loss: 0.42509538 |
|loss: 0.42554227 |
|loss: 0.4285382 |
|loss: 0.42526147 |
|loss: 0.42435426 |
|loss: 0.4281709 |
|loss: 0.4273314 |
|loss: 0.42432752 |
|loss: 0.42

|loss: 0.42596522 |
|loss: 0.43315193 |
|loss: 0.4237394 |
|loss: 0.42750257 |
|loss: 0.4323942 |
|loss: 0.42510447 |
|loss: 0.42596778 |
|loss: 0.43195727 |
|loss: 0.42604506 |
|loss: 0.4246666 |
|loss: 0.43148348 |
|loss: 0.42523703 |
|loss: 0.42393798 |
|loss: 0.4295391 |
|loss: 0.42436892 |
|loss: 0.42533565 |
|loss: 0.4285722 |
|loss: 0.42480242 |
|loss: 0.42503312 |
|loss: 0.43163303 |
|loss: 0.42428455 |
|loss: 0.42523187 |
|loss: 0.42868984 |
|loss: 0.4232111 |
|loss: 0.42782602 |
|loss: 0.43141368 |
|loss: 0.4248458 |
|loss: 0.42590195 |
|loss: 0.42811435 |
|loss: 0.42365158 |
|loss: 0.42566058 |
|loss: 0.42930388 |
|loss: 0.4262665 |
|loss: 0.42564246 |
|loss: 0.42808142 |
|loss: 0.4255831 |
|loss: 0.4254445 |
|loss: 0.42783922 |
|loss: 0.42677245 |
|loss: 0.42574355 |
|loss: 0.42582065 |
|loss: 0.4286133 |
|loss: 0.4256311 |
|loss: 0.42510724 |
|loss: 0.42725626 |
|loss: 0.4276399 |
|loss: 0.424911 |
|loss: 0.42510864 |
|loss: 0.4291696 |
|loss: 0.4264305 |
|loss: 0.42476878

|loss: 0.430937 |
|loss: 0.42441222 |
|loss: 0.4223808 |
|loss: 0.4298111 |
|loss: 0.42555365 |
|loss: 0.42257398 |
|loss: 0.4309386 |
|loss: 0.42469555 |
|loss: 0.42299902 |
|loss: 0.42802194 |
|loss: 0.42535806 |
|loss: 0.4226329 |
|loss: 0.42870274 |
|loss: 0.42603478 |
|loss: 0.42366573 |
|loss: 0.42878243 |
|loss: 0.4249396 |
|loss: 0.4236452 |
|loss: 0.4300877 |
|loss: 0.42498392 |
|loss: 0.42311132 |
|loss: 0.4282727 |
|loss: 0.4243418 |
|loss: 0.4236049 |
|loss: 0.42946962 |
|loss: 0.42401454 |
|loss: 0.42363897 |
|loss: 0.42825627 |
|loss: 0.42460483 |
|loss: 0.42569327 |
|loss: 0.42910492 |
|loss: 0.42440426 |
|loss: 0.4233823 |
|loss: 0.42998746 |
|loss: 0.42445856 |
|loss: 0.4236651 |
|loss: 0.4312145 |
|loss: 0.4245488 |
|loss: 0.4234893 |
|loss: 0.4295283 |
|loss: 0.42439288 |
|loss: 0.42396325 |
|loss: 0.4303955 |
|loss: 0.42442885 |
|loss: 0.423007 |
|loss: 0.42845434 |
|loss: 0.4238785 |
|loss: 0.42354748 |
|loss: 0.42913872 |
|loss: 0.425003 |
|loss: 0.42408746 |
|los

|loss: 0.4291513 |
|loss: 0.42644644 |
|loss: 0.42415679 |
|loss: 0.42631528 |
|loss: 0.42642707 |
|loss: 0.42488393 |
|loss: 0.4241284 |
|loss: 0.4279893 |
|loss: 0.42645463 |
|loss: 0.42396754 |
|loss: 0.42737037 |
|loss: 0.42670524 |
|loss: 0.42479077 |
|loss: 0.4237043 |
|loss: 0.4285446 |
|loss: 0.42643693 |
|loss: 0.42399687 |
|loss: 0.4272254 |
|loss: 0.42669016 |
|loss: 0.42436442 |
|loss: 0.42415375 |
|loss: 0.42872652 |
|loss: 0.42685476 |
|loss: 0.4233773 |
|loss: 0.42760968 |
|loss: 0.42625776 |
|loss: 0.42365515 |
|loss: 0.4240854 |
|loss: 0.42963728 |
|loss: 0.42564785 |
|loss: 0.4231864 |
|loss: 0.428938 |
|loss: 0.4248975 |
|loss: 0.42309722 |
|loss: 0.42626148 |
|loss: 0.42891046 |
|loss: 0.42445332 |
|loss: 0.4246047 |
|loss: 0.42855218 |
|loss: 0.4254416 |
|loss: 0.42419043 |
|loss: 0.42732003 |
|loss: 0.42727903 |
|loss: 0.42402598 |
|loss: 0.42354047 |
|loss: 0.42859343 |
|loss: 0.42524183 |
|loss: 0.4233609 |
|loss: 0.4279402 |
|loss: 0.42593727 |
|loss: 0.4240242

|loss: 0.42744783 |
|loss: 0.4276053 |
|loss: 0.42576686 |
|loss: 0.4250916 |
|loss: 0.42939758 |
|loss: 0.4272125 |
|loss: 0.42376277 |
|loss: 0.42553914 |
|loss: 0.42926955 |
|loss: 0.42554617 |
|loss: 0.42372957 |
|loss: 0.4298304 |
|loss: 0.42652044 |
|loss: 0.4238607 |
|loss: 0.42711425 |
|loss: 0.42728055 |
|loss: 0.4260584 |
|loss: 0.42587003 |
|loss: 0.4289885 |
|loss: 0.42682445 |
|loss: 0.42410094 |
|loss: 0.42654973 |
|loss: 0.42972735 |
|loss: 0.42547524 |
|loss: 0.42459413 |
|loss: 0.42966914 |
|loss: 0.42726994 |
|loss: 0.42576468 |
|loss: 0.42633316 |
|loss: 0.4292817 |
|loss: 0.4268642 |
|loss: 0.42477047 |
|loss: 0.4273889 |
|loss: 0.42764413 |
|loss: 0.42663938 |
|loss: 0.42615113 |
|loss: 0.42950186 |
|loss: 0.42617062 |
|loss: 0.42495292 |
|loss: 0.42766535 |
|loss: 0.42854053 |
|loss: 0.42434865 |
|loss: 0.42446446 |
|loss: 0.43060932 |
|loss: 0.42681625 |
|loss: 0.42429495 |
|loss: 0.42860994 |
|loss: 0.42792708 |
|loss: 0.4245145 |
|loss: 0.42561796 |
|loss: 0.43

KeyboardInterrupt: 