In [3]:
import json
import pickle as pk
from pprint import pprint
with open("BeiAQ.json","rb") as file:
    obj = pk.load(file)
    #print(obj[:10])
a = list()
for data in obj:
    if data['Month'] <= 6 and data['Month'] >= 3 and data['stationName'] == 'yanqin_aq':
        a.append(data)
print(len(a))
pprint(a[-10:])

112
[{'Date': '2017-6-22',
  'Day': 22,
  'Month': 6,
  'Year': 2017,
  '_id': ObjectId('5adaf6a550fc20ca07705b56'),
  'latitude': 40.453,
  'longitude': 115.97200000000001,
  'stationName': 'yanqin_aq',
  'valueByHour': {'0': {'CO': 0.7,
                        'NO2': 19.0,
                        'O3': 102.0,
                        'PM10': 30.0,
                        'PM25': 21.0,
                        'SO2': 2.0},
                  '1': {'CO': 0.7,
                        'NO2': 16.0,
                        'O3': 111.0,
                        'PM10': nan,
                        'PM25': 18.0,
                        'SO2': 2.0},
                  '10': {'CO': 0.9,
                         'NO2': 26.0,
                         'O3': 107.0,
                         'PM10': 6.0,
                         'PM25': nan,
                         'SO2': 2.0},
                  '11': {'CO': 0.9,
                         'NO2': 23.0,
                         'O3': 105.0,
               

                        'PM10': 21.0,
                        'PM25': 10.0,
                        'SO2': 3.0},
                  '9': {'CO': 0.2,
                        'NO2': 8.0,
                        'O3': 109.0,
                        'PM10': 18.0,
                        'PM25': 9.0,
                        'SO2': 3.0}}},
 {'Date': '2017-6-20',
  'Day': 20,
  'Month': 6,
  'Year': 2017,
  '_id': ObjectId('5adaf6a550fc20ca07705dde'),
  'latitude': 40.453,
  'longitude': 115.97200000000001,
  'stationName': 'yanqin_aq',
  'valueByHour': {'0': {'CO': 0.7,
                        'NO2': 42.0,
                        'O3': 66.0,
                        'PM10': 85.0,
                        'PM25': 37.0,
                        'SO2': 4.0},
                  '1': {'CO': 0.7,
                        'NO2': 19.0,
                        'O3': 132.0,
                        'PM10': 96.0,
                        'PM25': 51.0,
                        'SO2': 5.0},
                  '10'

In [119]:
import tqdm
from datetime import date
from datetime import datetime
lat = set()
lon = set()
for data in a:
    lat.add(round(data['latitude'],1))
    lon.add(round(data['longitude'],1))
    #if round(data['longitude'],1) == 117.1:
        #pprint(data)
lat = sorted(lat)
lon = sorted(lon)
pprint(lat)
pprint(lon)
def function(a):
    print(a)
    return a.keys()
#Build the datetime object
for obj in a:
    obj['Date'] = date(obj['Year'],obj['Month'],obj['Day'])
    obj['valueByHour'] = {int(key):obj['valueByHour'][key] for key in obj['valueByHour']}
#pprint(a[-1])

[39.5, 39.6, 39.7, 39.8, 39.9, 40.0, 40.1, 40.2, 40.3, 40.4, 40.5]
[116.0, 116.1, 116.2, 116.3, 116.4, 116.5, 116.6, 116.7, 116.8, 116.9, 117.1]


In [183]:
TEMP = {lon[i]:None for i in range(0,len(lon))}
for key in TEMP:
    TEMP[key] = {lat[i]:None for i in range(0,len(lat))}
    for key_2 in TEMP[key]:
        TEMP[key][key_2] = np.zeros((date(2017,7,1) - date(2017,3,1)).days * 24)
for data in a:
    lat_key = round(data['latitude'],1)
    lon_key = round(data['longitude'],1)
    for i in range(0,24):
        target_hour = (data['Date'] - date(2017,3,1)).days * 24 + i
        try:
            if not np.isnan(data['valueByHour'][i]['PM25']):
                TEMP[lon_key][lat_key][target_hour] = data['valueByHour'][i]['PM25']
        except:
            print(i,"Error")

16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
1 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
13 Error
14 Error
15 Error
18 Error
19 Error
20 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
2 Error
4 Error
5 Error
7 Error
8 Error
9 Error
11 Error
14 Error
16 Error
20 Error
22 Error
23 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
1 Error
8 Error
9 Error
10 Error
15 Error
16 Error
17 Error
19 Error
20 Error
21 Error
22 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
15 Error
16 Error
19 Error
20 Error
23 Error
0 Error
9 Error
10 Error
11 Error
12 Error
13 Error

20 Error
0 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
23 Error
1 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
13 Error
14 Error
15 Error
18 Error
19 Error
20 Error
0 Error
2 Error
0 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
2 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
0 Error
1 Error
2 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
14 Error
17 Error
18 Error
21 Error
22 Error
23 Error
0 Error
1 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
13 Error
14 Error
15 Error
18 Error
19 Error
20 Error
15 Error
16 Error
19 Error
20 Error
23 Error
15 Error
2 Error
16 Error
1 Error
3 Error
20 Error
0 Error
1 Error
8 Error
9 Error
10 Error
15 Error
16 Error
17 Error
19 Error
20 Error
21 Error

16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
14 Error
17 Error
18 Error
21 Error
22 Error
23 Error
0 Error
1 Error
2 Error
3 Error
4 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
1 Error
8 Error
9 Error
10 Error
15 Error
16 Error
17 Error
19 Error
20 Error
21 Error
22 Error
2 Error
2 Error
15 Error
16 Error
19 Error
20 Error
23 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
2 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
20 Error
2 Error
5 Error
6 Error
8 Error
9 Error
10 Error
11 Error
12 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 

23 Error
0 Error
1 Error
8 Error
9 Error
10 Error
15 Error
16 Error
17 Error
19 Error
20 Error
21 Error
22 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
14 Error
17 Error
18 Error
21 Error
22 Error
23 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
23 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
16 Error
20 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error


15 Error
16 Error
19 Error
20 Error
23 Error
0 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
20 Error
2 Error
4 Error
5 Error
7 Error
8 Error
9 Error
11 Error
14 Error
16 Error
20 Error
22 Error
23 Error
0 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
0 Error
1 Error
2 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
1 Error
3 Error
0 Error
2 Error
4 Error
5 Error
6 Error
7 Error
16 Error
1 Error
3 Error
4 Error
5 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
13 Error
14 Error
15 Error
18 Error
19 Error
20 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
0 Error
3 Error
4 Error
5 Erro

7 Error
9 Error
21 Error
22 Error
23 Error
2 Error
4 Error
5 Error
7 Error
8 Error
9 Error
11 Error
14 Error
16 Error
20 Error
22 Error
23 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
10 Error
11 Error
12 Error
13 Error
0 Error
1 Error
8 Error
9 Error
10 Error
15 Error
16 Error
17 Error
19 Error
20 Error
21 Error
22 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
23 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
2 Error
5 Error
6 Error
8 Error
9 Error
10 Error
11 Error
12 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
0 Error
3 Error
4 Error
5 Error
7 Error
8 Error
11 Error
12 Error
16 Error
17 Error
19 Error
20 Error
23 Error
2 Error
3 Error
4 Error
7 Error
9 Error
21 Error
22

2 Error
5 Error
6 Error
8 Error
9 Error
10 Error
11 Error
12 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
23 Error
2 Error
3 Error
4 Error
7 Error
9 Error
21 Error
22 Error
23 Error
1 Error
3 Error
4 Error
5 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
2 Error
3 Error
4 Error
7 Error
8 Error
9 Error
10 Error
11 Error
12 Error
13 Error
14 Error
15 Error
16 Error
17 Error
18 Error
19 Error
20 Error
21 Error
22 Error
23 Error
0 Error
1 Error
2 Error
3 Error
4 Error
6 Error
7 Error
8 Error
9 Error
10 Error
11 Error
15 Error
16 Error
17 Error
18 Error
19 Error
21 Error
22 Error
23 Error
0 Error
1 Error
4 Error
5 Error
6 Error
11 Error
12 Error
13 Error
20 Error
21 Error
20 Error
0 Error
2 Error
5 Error
6 Er

In [194]:
print(TEMP[116.3][39.5][-10:])
import pickle as pk
with open("PM25_Realdata.pkl","wb") as file:
    pk.dump(TEMP,file)
print("open")

[56. 51. 54. 56. 54. 53. 60. 83. 70. 72.]
open


In [179]:
import numpy as np
np.set_printoptions(threshold=np.nan)
date_count = (date(2017,7,1) - date(2017,3,1)).days
All_data = np.zeros((date_count * 24,len(lon),len(lat)),dtype=np.float32)
lat_index = {lat[i]:i for i in range(0,len(lat))}
lon_index = {lon[i]:i for i in range(0,len(lon))}
print(lat_index)
print(lon_index)
for data in a :
    for i in range(0,24):
        target_hour = (data['Date'] - date(2017,3,1)).days * 24 + i
        target_lon = lat_index[round(data['latitude'],1)]
        target_lat = lon_index[round(data['longitude'],1)]
        temp = All_data[target_hour][target_lon][target_lat]
        try:
            if not np.isnan(data['valueByHour'][i]['PM25']):
                if temp == 0.:
                    All_data[target_hour][target_lon][target_lat] = data['valueByHour'][i]['PM25']
                else:
                    All_data[target_hour][target_lon][target_lat] = (temp + data['valueByHour'][i]['PM25'])  / 2
        except:
            All_data[target_hour][target_lon][target_lat] = 0
            pass
pprint(All_data[:100])

{39.5: 0, 39.6: 1, 39.7: 2, 39.8: 3, 39.9: 4, 40.0: 5, 40.1: 6, 40.2: 7, 40.3: 8, 40.4: 9, 40.5: 10}
{116.0: 0, 116.1: 1, 116.2: 2, 116.3: 3, 116.4: 4, 116.5: 5, 116.6: 6, 116.7: 7, 116.8: 8, 116.9: 9, 117.1: 10}
array([[[  0.     ,   0.     ,   0.     ,   7.     ,   0.     ,
           0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
           0.     ],
        [ 10.     ,   0.     ,   0.     ,   0.     ,   0.     ,
           0.     ,   0.     ,   0.     ,   0.     ,   0.     ,
           0.     ],
        [  0.     ,   8.     ,   0.     ,   0.     ,   7.     ,
           0.     ,   0.     ,   0.     ,   7.     ,   0.     ,
           0.     ],
        [  0.     ,   6.     ,   0.     ,   0.     ,   0.     ,
           4.     ,   0.     ,   0.     ,   0.     ,   0.     ,
           0.     ],
        [  0.     ,  13.     ,   5.     ,   7.     ,   5.96875,
           6.     ,   0.     ,   4.     ,   0.     ,   0.     ,
           0.     ],
        [  0.     ,   0.     ,   3.     , 

In [178]:
for data in a:
    if data['stationName'] == 'badaling_aq' and data['Date'] == date(2017,3,9):
        print(data['valueByHour'][3])
    

{'CO': nan, 'PM10': nan, 'PM25': nan, 'SO2': nan, 'NO2': nan, 'O3': nan}


In [ ]:
class data_point:
    def __init__(self,lat = 0,lon = 0):
        self.lat = lat
        self.lon = lon
        self.data_list = np.empty(((date(2017,7,1) - date(2017,3,1)).days * 24))
a = data_point[len(lat_index) * len(lon_index)]
cursor = 0
for key_lat in lat_index:
    for key_lon in lon_index:
        a[cursor].lat = key_lat
        a[cursor].lon = key_lon
        a[cursor]

In [24]:
import glob
import time
import pandas as pd
import urllib.parse
import getpass
from pymongo import MongoClient
from tqdm import tqdm
from pprint import pprint

username = urllib.parse.quote_plus('ryuk')
pwd_input = getpass.getpass('Input password for mongodb:')
password = urllib.parse.quote_plus(pwd_input)
client = MongoClient('mongodb://%s:%s@140.116.164.187:27017/chinaAir' % (username, password))
client = client['chinaAir']
BeiHeight = client['BeiHeight']
All_height_data = list()
for data in BeiHeight.find({"$and":[{"longitude":{"$lt": 117.3}},
                                    {"longitude":{"$gt": 115.2}},
                                    {"latitude":{"$lt": 40.3}},
                                    {"latitude":{"$gt": 39.6}}]}):
    #pprint(data)
    All_height_data.append(data)
print("ok!")
    


Input password for mongodb:········
ok!


In [25]:
import pickle as pk
with open("All_height_data_1hr.pk","wb") as file:
    pk.dump(All_height_data,file)
print("ok!")

ok!


In [26]:
with open("All_height_data_1hr.pk","rb") as file:
    a = pk.load(file)
pprint(a[-1])

{'_id': ObjectId('5ae019a950fc202dcd53e02f'),
 'elevation': 1600.509399414062,
 'latitude': 39.986486486486484,
 'longitude': 115.29411764705883}


In [7]:
with open("PM25_Realdata.pkl","rb") as file:
    data = pk.load(file)
print(data[116.0][39.5][-10:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
